### ISSUE TITLE
سؤال دربارهٔ پروانه

### ISSUE THREAD

**Issue by ekm507** [AmirMohamadBabaee/power-method-linear-algebra#1]
درود
دربارهٔ پروانهٔ این مخزن ۲ تا سؤال دارم.
نخست این که چرا به‌جای پروانه‌های نرم‌افزاری از پروانه‌های آثار فرهنگی (یعنی creative commons) برای پروژه استفاده کرده‌اید.
دوم این که چرا به‌جای پروانه‌های کپی‌لفتی (مثل GPL یا CC-BY-SA) از پروانهٔ سهل‌گیر CC-0 استفاده کرده‌اید که نه‌تنها آزاد ماندن پروژه را تضمین نمی‌کند بلکه به دیگران اجازه می‌دهد بدون ارجاع به نام شما از این پروژه در کارهای خود استفاده کنند.
با سپاس.

**Comment by AmirMohamadBabaee** [comment]
سلام 
وقت شما بخیر
این ریپو صرفا دارای یک نوتبوک مرتبط با پروژه دانشگاهی بوده و دلیلی وجود نداشت که برای این پروژه لایسنس محدود‌تری استفاده بشه. ممنون از اینکه به این موضوع توجه داشتین.
روز خوبی داشته باشین
